apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-attrition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-attrition
  template:
    metadata:
      labels:
        app: emp-attrition
    spec:
      containers:
        - name: emp-attrition
          image: emp_attrition:latest
          imagePullPolicy: Never